# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='images/photos')),
            ],
            options={
                'verbose_name': 'Miasto',
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='images/photos/')),
            ],
            options={
                'verbose_name': 'Kontynent',
                'verbose_name_plural': 'Kontynenty',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='images/photos')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Continent')),
            ],
            options={
                'verbose_name': 'Kraj',
                'verbose_name_plural': 'Kraje',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country'),
        ),
    ]
