# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160215_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='about',
            field=models.TextField(default='Country', max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(),
        ),
    ]
